import '@/styles/globals.scss';

export const metadata = {
  title: 'Newsletter sign up component | Adrian Czubaty',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
